<div class="pd2 cf">
    <h4 class="fl">接口说明</h4>

</div>
<div class="col-sm-12">
    <h1>接口地址：<?=$domain_url?>/api</h1>

    <hr>
    <h2>一、上传接口</h2>
    <p>1、调用示例：<?=$domain_url?>/api/set?only=0&typeid=9&typedataid=4&data=0000001</p>
    <p>2、参数说明：</p>
    <p>2.2、only：是否过滤重复数据；非必传；参数值0或1；默认值0；如果传1上传耗时稍长,</p>
    <p>2.3、typeid：项目ID；必传</p>
    <p>2.4、typedataid：数据ID；选传</p>
    <p>2.8、data：上传数据；必传</p>
    <p>2.8、img：上传图片；选传</p>
    <p>2.8、img1：上传图片1；选传</p>
    <p>3、返回值说明：</p>
    <p>3.1、成功返回：OK|项目ID|数据ID</p>
    <p>3.2、失败返回：ERR|失败原因  注意：如果返回空请重新提交</p>

    <hr>
    <h2>二、提取接口</h2>
    <p>1、调用示例：<?=$domain_url?>/api/get?typeid=9&rand=1</p>
    <p>2、参数说明：</p>
    <p>2.1、typeid：项目ID；必传；用户端查看</p>
    <p>2.4、typedataid：数据ID；选传</p>
    <p>2.2、rand：
        <br/>rand:0, typedataid 提取单条数据：<?=$domain_url?>/api/get?rand=0&typeid=26&typedataid=25814
        <br/>rand:0 随机提取一条数据：<?=$domain_url?>/api/get?rand=0&typeid=26
        <br/>rand:1 获取随机一条未提取数据且更新状态为已提取：<?=$domain_url?>/api/get?rand=1&typeid=26
        <br/>rand:不传, typedataid:不传 获取最新一条未提取数据且更新状态为已提取：<?=$domain_url?>/api/get?typeid=26
        <br/>rand:不传, typedataid:83 获取单条未提取数据且更新状态为已提取：<?=$domain_url?>/api/get?typeid=26&typedataid=83
    </p>
    <p>3.1、成功返回：OK|ID|数据|项目ID|数据ID|创建时间</p>
    <p>3.2、失败返回：ERR|失败原因</p>

    <hr>
    <h2>三、获取数量接口</h2>
    <p>1、调用示例：<?=$domain_url?>/api/getcount?typeid=9&status=1</p>
    <p>2、参数说明：</p>
    <p>2.2、status：是否已提取；非必传；参数值1或2；1:未提取,2,已提取</p>
    <p>2.3、typeid：项目ID；必传</p>
    <p>3、返回值说明：</p>
    <p>3.1、成功返回：OK|数量</p>
    <p>3.2、失败返回：ERR|失败原因  注意：如果返回空请重新提交</p>

    <hr>
    <h2>四、删除接口</h2>
    <p>1、调用示例：<?=$domain_url?>/api/del?typeid=24&typedataid=1</p>
    <p>2、参数说明：</p>
    <p>2.3、typeid：项目ID；必传</p>
    <p>2.4、typedataid：数据ID；必传</p>
    <p>3、返回值说明：</p>
    <p>3.1、成功返回：OK|</p>
    <p>3.2、失败返回：ERR|失败原因  注意：如果返回空请重新提交</p>

</div>