<div class="pd2 cf">
    <h4 class="fl">接口说明</h4>
</div>
<div class="col-sm-12">
    <h2>1 上传数据</h2>
    <h3>1.1 请求方式</h3>
    <p>请求URL：<?=$domain_url?>/v1/data/post</p>
    <p>请求访求：POST</p>
    <h3>1.2 请求参数</h3>
    <table>
        <thead><tr><th style="text-align:left">名称</th><th>描述</th></tr></thead>
        <tbody>
            <tr>
                <td style="text-align:left"><code>Tid</code></td>
                <td>项目id</td>
            </tr>
            <tr>
                <td style="text-align:left"><code>Orderid</code></td>
                <td>序号 当有值时更新数据</td>
            </tr>
            <tr>
                <td style="text-align:left"><code>Img</code></td>
                <td>图片base64编码</td>
            </tr>
            <tr>
                <td style="text-align:left"><code>Img1</code></td>
                <td>图片1base64编码</td>
            </tr>
            <tr>
                <td style="text-align:left"><code>File</code></td>
                <td>文件base64编码</td>
            </tr>
            <tr>
                <td style="text-align:left"><code>FileName</code></td>
                <td>文件名后辍 如.tar.gz</td>
            </tr>
            <tr>
                <td style="text-align:left"><code>Mobile</code></td>
                <td>手机号</td>
            </tr>
            <tr>
                <td style="text-align:left"><code>Account</code></td>
                <td>用户名</td>
            </tr>
            <tr>
                <td style="text-align:left"><code>Password</code></td>
                <td>密码</td>
            </tr>
            <tr>
                <td style="text-align:left"><code>Ip</code></td>
                <td>ip</td>
            </tr>
            <tr>
                <td style="text-align:left"><code>IpAttribution</code></td>
                <td>ip归属地</td>
            </tr>
            <tr>
                <td style="text-align:left"><code>DeviceMode</code></td>
                <td>设备型号</td>
            </tr>
            <tr>
                <td style="text-align:left"><code>DeviceVersion</code></td>
                <td>设备系统版本</td>
            </tr>
            <tr>
                <td style="text-align:left"><code>Imsi</code></td>
                <td>imsi</td>
            </tr>
            <tr>
                <td style="text-align:left"><code>SimId</code></td>
                <td>SimId</td>
            </tr>
            <tr>
                <td style="text-align:left"><code>Name</code></td>
                <td>姓名</td>
            </tr>
            <tr>
                <td style="text-align:left"><code>IdCard</code></td>
                <td>身份证号码</td>
            </tr>
        </tbody>
    </table>
    <hr />
    <h2>2 获取数据</h2>
    <h3>2.1 请求方式</h3>
    <p>请求URL：<?=$domain_url?>/v1/data/getone</p>
    <p>请求访求：GET</p>
    <h3>2.2 请求参数</h3>
    <table>
        <thead><tr><th style="text-align:left">名称</th><th>描述</th></tr></thead>
        <tbody>
            <tr>
                <td style="text-align:left"><code>Tid</code></td>
                <td>项目id</td>
            </tr>
            <tr>
                <td style="text-align:left"><code>Orderid</code></td>
                <td>序号 有值时获指定数据</td>
            </tr>
            <tr>
                <td style="text-align:left"><code>Rand</code></td>
                <td>是否随机 1 是</td>
            </tr>
            <tr>
                <td style="text-align:left"><code>Update</code></td>
                <td>是否更新为已提取 1 更新</td>
            </tr>
        </tbody>
    </table>
    <hr />
    <h2>3 获取项目总数</h2>
    <h3>3.1 请求方式</h3>
    <p>请求URL：<?=$domain_url?>/v1/data/count</p>
    <p>请求访求：GET</p>
    <h3>3.2 请求参数</h3>
    <table>
        <thead><tr><th style="text-align:left">名称</th><th>描述</th></tr></thead>
        <tbody>
            <tr>
                <td style="text-align:left"><code>Tid</code></td>
                <td>项目id</td>
            </tr>
            <tr>
                <td style="text-align:left"><code>Day</code></td>
                <td>获取多少天前零点到现在的数据</td>
            </tr>
            <tr>
                <td style="text-align:left"><code>Status</code></td>
                <td>是否只获取已提取 1 是</td>
            </tr>
        </tbody>
    </table>

    <hr />
    <h2>返回说明</h2>
    <p>返回格式：JSON</p>
    <table>
        <thead><tr><th style="text-align:left">名称</th><th>描述</th></tr></thead>
        <tbody>
            <tr>
                <td style="text-align:left"><code>Code</code></td>
                <td>状态码 200 返回成功</td>
            </tr>
            <tr>
                <td style="text-align:left"><code>Msg</code></td>
                <td>错误信息</td>
            </tr>
            <tr>
                <td style="text-align:left"><code>Data</code></td>
                <td>具体数据</td>
            </tr>
        </tbody>
    </table>
</div>