<link href="/css/fileinput.css" media="all" rel="stylesheet" type="text/css" />
<script src="/js/fileinput.js" type="text/javascript"></script>
<div class="pd2 cf">
    <h4 class="fl">上传数据</h4>

</div>
<form class="navbar-form navbar-left" action="<?= $this->url->get('typedata/dataadd') ?>" method="post" role="form" enctype="multipart/form-data">
    <input type="hidden" name="<?= $this->security->getTokenKey() ?>" value="<?= $this->security->getToken() ?>"/>
    <div class="form-group mt0 "> 项目:
        <select class="form-control" id="typeid" name="typeid"  >
            <option  value="">请选择</option>
            <?php foreach ($type as $ptype): ?>
                <option  value='<?= $ptype->typeid;?>' <?php if (!empty($search) && $search['typeid'] == $ptype->typeid) echo 'selected'?>><?= $ptype->typeid;?>||<?= $ptype->typename;?></option>
            <?php endforeach; ?>
        </select>
        上传txt文件：<input name="name" type="file" id="av" style="display: inline-block" />
        <button type="submit" class="btn btn-flat btn-success">上传</button>
        <div>上传文件要求
            <ul>
                <li>文件名必须是英文或者拼音</li>
                <li>文件内容必须是utf8无bom格式</li>
                <li>上传文件格式：手机号,账号,密码,IP,IP地址,IMEI,设备型号,设备系统版本,IMSI,SimId,姓名,身份证</li>
                <li>文件模板：<a href="/static/dataadd.txt"  download="dataadd.txt">下载</a></li>
            </ul>
        </div>
    </div>

</form>