<?php

$params = $_GET;

$superAdmin = ($admin['id'] == 1 || $admin['id'] == 2);
?>
<script>
    function selectAll(o) {
        $("input:checkbox[name=ids]").each(function(){
            this.checked = o.checked;
        });

        return false;
    }

    function moveTypedata(type) {
        var ids = '';
        $("input:checkbox[name=ids]").each(function(index){
            if (this.checked) {
                ids += this.value + ',';
            }
        });

        window.location.href = "<?= $this->url->get('typedata/moveTypedata?ids=') ?>" + ids + '&type=' + type;
    }

    function exportSend() {
        $.getJSON(
            '<?php echo $this->url->get('typedata/outdata');?>',
            {
                typeid: $("#typeid").val(),
                status: $("#status").val(),
                sttime: $("#sttime").val(),
                endtime: $("#endtime").val(),
                data_unique: $("#data_unique:checked").val()
            },
            function(result){
                if (result.code != 200) {
                    alert(result.msg);
                    window.location.reload();
                }
            }
        );
    }
</script>
<script language="javascript" type="text/javascript" src="/static/js/My97DatePicker/WdatePicker.js"></script>
<div class="pd2 cf">
    <h4 class="fl">数据列表</h4>
    <?php if (!empty($admin['roles']['/typedata/index?addtype']) || $superAdmin):?>
        <a data-toggle="modal" data-target="#myModal" id="data" href="" class="btn btn-sm btn-success">添加项目</a>
    <?php endif;?>
    <?php if ($superAdmin):?>
        <!--<a href="<?/*= $this->url->get('typedata/outdata?status='.$search['status'].'&typeid='.$search['typeid'].'&sttime='.$search['sttime'].'&endtime='.$search['endtime'])."&data_unique=".$search['data_unique'].'&target='.$search['target'];*/?>" title="导出" class="btn btn-sm btn-success">导出</a>-->
        <a onclick="exportSend();" href="" data-toggle="modal" data-target="#modal_export" class="btn btn-sm btn-success">导出</a>
    <?php endif;?>
</div>
<form class="navbar-form navbar-left" action="<?= $this->url->get('typedata/index')?>" method="get" role="form">
    <div class="form-group mt0 ">
        项目<select class="form-control" id="typeid" name="typeid"  >
            <option value="">请选择</option>
            <?php foreach ($type as $ptype): ?>
                <option value='<?= $ptype->typeid;?>' <?php if ($search['typeid'] == $ptype->typeid) echo 'selected'?>><?= $ptype->typeid;?>|<?= $ptype->typename;?></option>
            <?php endforeach; ?>
        </select>
        提取<select class="form-control" id="status" name="status"  >
            <option value="0">请选择</option>
            <option value='1'<?php if ($search['status'] === '1') echo 'selected'?>>未提取</option>
            <option value="2"<?php if ($search['status'] == '2') echo 'selected'?>>已提取</option>
        </select>
        上传时间<input id="sttime"  class="form-control" name="sttime"  placeholder="开始日期" data-options="required:true,disabled:false" onclick="new WdatePicker({dateFmt:'yyyy-MM-dd HH:00:00'});" value="<?= $search['sttime'];?>" style="width: 142px;">
        -<input id="endtime" class="form-control" name="endtime"  placeholder="结束日期" data-options="required:true,disabled:false" onclick="new WdatePicker({dateFmt:'yyyy-MM-dd HH:00:00'});" value="<?= $search['endtime'];?>" style="width: 142px;">
        数据去重<input id="data_unique" name='data_unique' type="checkbox" <? if (!empty($search['data_unique'])) echo 'checked'?> value="1"/>
        <input type="hidden" name="target" value="<?=$search['target'] ?>">
        <button type="submit" class="btn btn-flat btn-success">搜索</button>
    </div>
</form>
<table class="table table-bordered text-left table-hover" style="table-layout: fixed; word-break: break-all;">
    <thead>
    <tr>
        <?php if ($superAdmin):?>
            <td width="64"><input type="checkbox" onclick="selectAll(this)"/>全选</td>
        <?php endif;?>
        <th width="64">id</th>
        <th width="64">序号</th>
        <th width="64" >提取</th>
        <th width="64">项目id</th>
        <th width="74">项目名称</th>
        <th width="150">图片</th>
        <th width="150">图片1</th>
        <th width="84">上传时间</th>
        <th width="84">更新时间</th>
        <th>数据</th>
        <?php if ($superAdmin):?>
            <th width="64"><button class="btn btn-sm btn-danger delete" onclick="moveTypedata('del');">删除</button></th>
        <?php endif;?>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($page->items as $item): ?>
        <tr>
            <?php if ($superAdmin):?>
                <td><input type="checkbox" name="ids" value="<?= $item->id;?>"></td>
            <?php endif;?>
            <td><?= $item->id;?></td>
            <td><?= $item->orderid;?></td>
            <td><?= $item->status=='1'?'未提取':'已提取';?></td>
            <td><?= $item->tid;?></td>
            <td><?= $typearrs[$item->tid];?></td>
            <td><? if ($item->img){echo '<img src="'.$item->img.'" width="136"/>';}?></td>
            <td><? if ($item->img1){echo '<img src="'.$item->img1.'" width="136"/>';}?></td>
            <td><?= date('Y-m-d H:i:s',$item->creattime);?></td>
            <td><?if ($item->updatetime){echo date('Y-m-d H:i:s',$item->updatetime);}?></td>
            <td><?= $item->data;?></td>
            <?php if ($superAdmin):?>
                <td><a href="<?= $this->url->get('typedata/moveTypedata?ids='.$item->id.'&type=del') ?>" class="btn btn-sm btn-danger delete">删除</a></td>
            <?php endif;?>
        </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<?php $this->partial("common/pages", array('url' => 'typedata/index?page=', 'page' => $page)) ?>
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">添加项目</h4>
            </div>
            <form class="form-horizontal" role="form" method="post" action="<?= $this->url->get('typedata/typeadd') ?>">
                <input type="hidden" name="<?= $this->security->getTokenKey() ?>" value="<?= $this->security->getToken() ?>"/>
                <div class="form-group">
                    <label class="col-xs-2 control-label">项目名称：</label>
                    <div class="col-xs-10">
                        <input type="text" name="typename" placeholder="项目名称" class="form-control" required=""  value="">
                    </div>
                </div>
                <button type="submit" class="btn btn-flat btn-info btn-lg btn-block">提交</button>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="modal_export" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">添加项目</h4>
            </div>
            <form class="form-horizontal" role="form" method="post" action="<?= $this->url->get('typedata/typeadd') ?>">
                <input type="hidden" name="<?= $this->security->getTokenKey() ?>" value="<?= $this->security->getToken() ?>"/>
                <div class="form-group">
                    <label class="col-xs-2 control-label">项目名称：</label>
                    <div class="col-xs-10">
                        <input type="text" name="typename" placeholder="项目名称" class="form-control" required=""  value="">
                    </div>
                </div>
                <button type="submit" class="btn btn-flat btn-info btn-lg btn-block">提交</button>
            </form>
        </div>
    </div>
</div>