<script>
    function edittype(id)
    {
        htmlobj1 = $.ajax({url: "<?= $this->url->get('typedata/edittype?typeid=') ?>" + id , async: false});
        $("#mymodel").html(htmlobj1.responseText);
    }

    function selectAll(o) {
        $("input:checkbox[name=typeid]").each(function(){
            this.checked = o.checked;
        });

        return false;
    }

    function batchAll(action) {
        typeid = '';
        $("input:checkbox[name=typeid]").each(function(index){
            if (this.checked) {
                typeid += this.value + ',';
            }
        });

        window.location.href = "/typedata/"+ action +"?typeid=" + typeid;
    }
</script>
<div class="pd2 cf">
    <h4 class="fl">项目管理</h4>

</div>
<table class="table table-bordered text-left table-hover">
    <thead>
    <tr>
        <td width="64"><input type="checkbox" onclick="selectAll(this)" />全选</td>
        <th>项目id</th>
        <th>项目名称</th>
        <th>创建时间</th>
        <th>更新时间</th>
        <th>操作</th>
    </tr>
    </thead>
    <tbody>
    <?php foreach ($type as $item): ?>
        <tr>
            <td class="text-left"><input type="checkbox" name="typeid" value="<?= $item->typeid;?>"></td>
            <td><?= $item->typeid;?></td>
            <td><?= $item->typename;?></td>
            <td><?if ($item->createtime){echo date('Y-m-d H:i:s',$item->createtime);}?></td>
            <td><?if ($item->updatetime){echo date('Y-m-d H:i:s',$item->updatetime);}?></td>
            <td>
                <?php if ($recycle):?>
                        <a href="<?= $this->url->get('typedata/deltype?typeid='.$item->typeid) ?>" class="btn btn-sm btn-danger delete">删除</a>
                        <a href="<?= $this->url->get('typedata/restortype?typeid='.$item->typeid) ?>" class="btn btn-sm btn-danger delete">恢复</a>
                        <a href="<?= $this->url->get('typedata/cleardata?typeid='.$item->typeid) ?>" class="btn btn-sm btn-danger delete">清除数据</a>
                <?php else:?>
                    <a onclick="edittype(<?= $item->typeid;?>)"  data-toggle="modal" data-target="#myModal" id="data_<?= $item->typeid;?>" class="btn btn-sm btn-success">修改</a>
                    <a href="<?= $this->url->get('typedata/recycletype?typeid='.$item->typeid) ?>" class="btn btn-sm btn-danger delete">移至回收站</a>
                    <a href="<?= $this->url->get('typedata/status1?typeid='.$item->typeid) ?>" class="btn btn-sm btn-danger delete">更新为未提取</a>
                    <a href="<?= $this->url->get('typedata/status2?typeid='.$item->typeid) ?>" class="btn btn-sm btn-danger delete">更新为已提取</a>
                <?php endif;?>
            </td>
        </tr>
    <?php endforeach; ?>
    <tr>
        <td class="text-left" colspan="6">
            <?php if ($recycle):?>
                    <button class="btn btn-sm btn-danger delete" onclick="batchAll('deltype');">删除</button>
                    <button class="btn btn-sm btn-danger delete" onclick="batchAll('restortype');">恢复</button>
                    <button class="btn btn-sm btn-danger delete" onclick="batchAll('cleardata');">清除数据</button>
            <?php else:?>
                <button class="btn btn-sm btn-danger delete" onclick="batchAll('recycletype');">移至回收站</button>
                <button class="btn btn-sm btn-danger delete" onclick="batchAll('status1');">更新为未提取</button>
                <button class="btn btn-sm btn-danger delete" onclick="batchAll('status2');">更新为已提取</button>
            <?php endif;?>
        </td>
    </tr>
    </tbody>
</table>
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title" id="myModalLabel">修改信息</h4>
            </div>
            <div id="mymodel" class="modal-body">
            </div>
        </div>
    </div>
</div>
