<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title><?= Phalcon\Tag::getTitle(FALSE) ?></title>
    <meta itemprop="name" content="<?= Phalcon\Tag::getTitle(FALSE) ?>"/>
    <meta itemprop="image" content="<?= @$logo; ?>" />
    <meta name="description" itemprop="description" content="<?= @$description?>" />
    <meta property="og:title" content="xiaozhang" />
    <meta property="og:image" content="<?=$domain_url?>/images/8131_22_0.png" />
    <?php $this->assets->outputCss() ?>
    <?php $this->assets->outputJs() ?>
</head>
<body class="<?= isset($bodystyle) ? $bodystyle : '' ?>">
<?= $this->getContent() ?>
</body>
</html>