<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title><?= Phalcon\Tag::getTitle(FALSE) ?></title>
    <meta itemprop="name" content="<?= Phalcon\Tag::getTitle(FALSE) ?>"/>
    <meta itemprop="image" content="<?= $logo; ?>" />
    <meta name="description" itemprop="description" content="<?= $description?>" />
    <?php $this->assets->outputCss() ?>
    <?php $this->assets->outputJs() ?>
    <?php if(stripos(\Phalcon\Arr::get($_SERVER, 'HTTP_HOST'), 'admin') === FALSE):?>

    <?php endif;?>
</head>
<body class="<?= isset($bodystyle) ? $bodystyle : '' ?>">
<?= $this->getContent() ?>
</body>
</html>