<style type="text/css">
    .loginbox {margin-top: 10%;}
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 col-md-offset-3 loginbox">


            <div class="panel panel-default">
                <div class="panel-heading">校长后台管理系统</div>
                <div class="panel-body">
                    <p class="alert alert-warning login-box-msg hide"><?php $this->flashSession->output() ?></p>
                    <form class="form-horizontal" role="form" method="POST" action="<?= $this->url->get('auth/check')?>">
                        <input type="hidden" name="<?= $this->security->getTokenKey() ?>" value="<?= $this->security->getToken()?>">

                        <div class="form-group">
                            <label for="mobile" class="col-md-4 control-label">账号</label>
                            <div class="input-group col-md-6">
                                <input name="username" type="text" class="form-control" placeholder="请输出账号">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>

                            </div>
                        </div>

                        <div class="form-group">
                            <label for="mobile" class="col-md-4 control-label">密码</label>
                            <div class="input-group col-md-6">
                                <input name="password" type="password" class="form-control" placeholder="请输出密码">
                                <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>

                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    <i class="fa fa-btn fa-sign-in"></i> 登录
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
