<h3 class="login-logo text-center">
    米多后台管理系统
</h3>
<div class="row">
    <p class="alert alert-warning login-box-msg hide"><?php $this->flashSession->output() ?></p>
    <form action="<?= $this->url->get('auth/check') ?>" method="post" class="login-form">

        <input type="hidden" name="<?= $this->security->getTokenKey() ?>" value="<?= $this->security->getToken() ?>">

        <div class="form-group has-feedback">
            <input name="username" type="text" class="form-control" placeholder="请输出账号">
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
        </div>
        <div class="form-group has-feedback">
            <input name="password" type="password" class="form-control" placeholder="请输出密码">
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
        </div>
        <button type="submit" class="btn btn-primary btn-block btn-flat">登录</button>
    </form>
</div>