
<?php
$geturl = $this->dispatcher->getControllerName() . '/' . $this->dispatcher->getActionName();
$namespace = $this->dispatcher->getNamespaceName();
$namespace = strtolower($namespace);
$controller = $this->dispatcher->getControllerName();
$action = $this->dispatcher->getActionName();

function accessAllow($uri)
{
    global $admin;

    return !empty($admin['roles'][$uri]) || $admin['id'] == 1 || $admin['id'] == 2; // id 1 超级管理员, id 2  老板账号
}
?>

<header class="main-header">
    <noscript>
        <div class="noscript-warning">
            Javascript is disabled in your web browser. Some features will not work properly.
        </div>
    </noscript>
    <a class="logo" href="/"><span>校长管理后台</span></a>
    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-left">
            <div class="hidden-xs">
                <ol class="nav navbar-top-links breadcrumb">
                    <li>
                        <a href="/">
                            <i class="fa fa-home"></i> </a>
                    </li>
                </ol>
            </div>
        </div>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown user-menu">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                        <i class="fa fa-user fa-fw" aria-hidden="true"></i> <i class="fa fa-caret-down" aria-hidden="true"></i>
                    </a>
                    <ul class="dropdown-menu dropdown-user">
                        <li><a href="<?=$this->url->get('auth/logout') ?>">退出登录</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

<aside class="main-sidebar">
    <section class="sidebar">
        <ul class="sidebar-menu">
            <li class="<?php if($controller=='typedata'):?>active<?php endif;?> first treeview">
                <a href="#">
                    <i class="fa fa-folder"></i>
                    <span>数据管理</span>
                    <span class="pull-right-container">
                        <i class="fa pull-right fa-angle-left"></i>
                    </span>
                </a>
                <ul class="<?php if($controller=='typedata'):?>active<?php endif;?> treeview-menu menu_level_1">
                    <?php if (accessAllow('/typedata/index') || !empty($admin['roles']['allow_type'])):?>
                        <li class="<?php if($controller=='typedata'&& $action=='index' && $target == 'index'):?>active<?php endif;?> first">
                            <a href="<?= $this->url->get('typedata/index')?>">
                                <i class="fa fa-angle-double-right" aria-hidden="true"></i>数据列表
                            </a>
                        </li>
                    <?php endif;?>
                    <?php if (accessAllow('/typedata/dataadd')):?>
                    <li class="<?php if($controller=='typedata'&& $action=='dataadd'):?>active<?php endif;?> first">
                        <a href="<?= $this->url->get('typedata/dataadd') ?>">
                            <i class="fa fa-angle-double-right" aria-hidden="true"></i>上传数据
                        </a>
                    </li>
                    <?php endif;?>
                    <?php if (accessAllow('/typedata/api')):?>
                    <li class="<?php if($controller=='typedata'&& $action=='api'):?>active<?php endif;?> first">
                        <a href="<?= $this->url->get('typedata/api') ?>">
                            <i class="fa fa-angle-double-right" aria-hidden="true"></i>接口说明
                        </a>
                    </li>
                    <?php endif;?>
                    <?php if (accessAllow('/typedata/typead')):?>
                    <li class="<?php if($controller=='typedata'&& $action=='typead'  && empty($_GET['recycle'])):?>active<?php endif;?> first">
                        <a href="<?= $this->url->get('typedata/typead') ?>">
                            <i class="fa fa-angle-double-right" aria-hidden="true"></i>项目管理
                        </a>
                    </li>
                    <?php endif;?>
                    <?php if (accessAllow('/typedata/typead?recycle')):?>
                    <li class="<?php if($controller=='typedata'&& $action=='typead' && !empty($_GET['recycle'])):?>active<?php endif;?> first">
                        <a href="<?= $this->url->get('typedata/typead').'?recycle=1' ?>">
                            <i class="fa fa-angle-double-right" aria-hidden="true"></i>项目管理（回收站）
                        </a>
                    </li>
                    <?php endif;?>
                </ul>
            </li>

            <?php if (accessAllow('admin')):?>
            <li class="<?php if($controller=='admin'):?>active<?php endif;?> first treeview">
                <a href="#">
                    <i class="fa fa-folder"></i>
                    <span>用户管理</span>
                    <span class="pull-right-container">
                        <i class="fa pull-right fa-angle-left"></i>
                    </span>
                </a>
                <ul class="<?php if($controller=='admin'):?>active<?php endif;?> treeview-menu menu_level_1">
                    <li class="<?php if($controller=='admin'&& $action=='adminlist'):?>active<?php endif;?> first">
                        <a href="<?= $this->url->get('admin/adminlist') ?>">
                            <i class="fa fa-angle-double-right" aria-hidden="true"></i>管理员列表
                        </a>
                    </li>
                    <li class="<?php if($controller=='admin'&& $action=='addadmin'):?>active<?php endif;?> first">
                        <a href="<?= $this->url->get('admin/addadmin') ?>">
                            <i class="fa fa-angle-double-right" aria-hidden="true"></i>添加管理员
                        </a>
                    </li>
                    <li class="<?php if($controller=='admin'&& $action=='applist'):?>active<?php endif;?> first">
                        <a href="<?= $this->url->get('admin/applist') ?>">
                            <i class="fa fa-angle-double-right" aria-hidden="true"></i>app包管理
                        </a>
                    </li>
                </ul>
            </li>
            <?php endif;?>
        </ul>
    </section>
</aside>
