
<?php if ($this->session->get('admin_auth')) { $this->partial("common/nav"); ?>
    <div class="wrapper container">
        <div class="row">
            <section class="content-header">
                <?php $this->flashSession->output() ?>
                <?= $this->getContent() ?>
            </section>
        </div>
    </div>
<?php } else { ?>
    <div class="wrapper container">
        <?= $this->getContent() ?>
        <p class="text-center">Copyright &copy; 2014-<?=date('Y')?> 版权所有 <a href="http://ad.miduo.com/auth/index" class="beian">校长科技</a></p>
    </div>
<?php } ?>
