<?php
if ($this->session->get('admin_auth'))
{
?>
    <div class="sonata-bc skin-black fixed wrapper">
        <?php $this->partial("common/nav") ?>
        <div class="content-wrapper">
            <section class="content">
                <div class="row">
                    <div class="col-xs-12 col-md-12">
                        <div class="box box-primary">
                            <div class="box-body table-responsive no-padding" style="margin-top: 16px;margin-left: 10px;">
                                <?php $this->flashSession->output() ?>
                                <?= $this->getContent() ?>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
        </div>
    </div>
<?php } else { ?>
        <?= $this->getContent() ?>
<?php } ?>
