<form class="form-horizontal gameadd-form" role="form" action="<?= $this->url->get('admin/addadmin') ?>" method="post">
    <input type="hidden" name="<?= $this->security->getTokenKey() ?>" value="<?= $this->security->getToken() ?>"/>
    <input type="hidden" name="id" value="<?=@$user['id']?>"/>


    <div class="form-group">
        <label class="col-xs-1">用户名：</label>
        <div class="col-xs-3">
            <input type="text" name="username" class="form-control" <?php if(!empty($user['id'])):?> value="<?=$user['username']?>" disabled<?php endif;?>/>
        </div>
    </div>
    <div class="form-group">
        <label class="col-xs-1">密码：</label>
        <div class="col-xs-3">
            <input type="text" name="password" placeholder="输入密码" class="form-control">
        </div>
    </div>

    <?php if (empty($user['id']) || ($user['id'] !=1 && $user['id'] != 2)):?>
    <div class="form-group">
        <label class="col-xs-1"></label>
        <div class="col-xs-10">
            <label class="checkbox">
                <input type="checkbox" name="roles[/typedata/typead]" class="checkbox" value="1" <?php if(!empty($user['roles']['/typedata/typead'])) echo "checked";?>>是否能操作项目管理
            </label>
        </div>
    </div>

    <div class="form-group">
        <label class="col-xs-1"></label>
        <div class="col-xs-10">
            <label class="checkbox">
                <input type="checkbox" name="roles[/typedata/index]" class="checkbox" value="1" <?php if(!empty($user['roles']['/typedata/index'])) echo "checked";?>>是否能查看项目数据
            </label>
        </div>
    </div>

    <div class="form-group">
        <label class="col-xs-1"></label>
        <div class="col-xs-10">
            <label class="checkbox">
                <input type="checkbox" name="roles[/typedata/typead?recycle]" class="checkbox" value="1" <?php if(!empty($user['roles']['/typedata/typead?recycle'])) echo "checked";?>>是否能操作回收站
            </label>
        </div>
    </div>

    <div class="form-group">
        <label class="col-xs-1"></label>
        <div class="col-xs-10">
            <label class="checkbox">
                <input type="checkbox" name="roles[/typedata/index?addtype]" class="checkbox" value="1" <?php if(!empty($user['roles']['/typedata/index?addtype'])) echo "checked";?>>是否能添加项目
            </label>
        </div>
    </div>

    <div class="form-group">
        <label class="col-xs-1"></label>
        <div class="col-xs-10">
            <label class="checkbox">
                <input type="checkbox" name="roles[/typedata/index?export]" class="checkbox" value="1" <?php if(!empty($user['roles']['/typedata/index?export'])) echo "checked";?>>是否能导出数据
            </label>
        </div>
    </div>

    <div class="form-group">
        <label class="col-xs-1"></label>
        <div class="col-xs-10">
            <label class="checkbox">
                <input type="checkbox" name="roles[/typedata/dataadd]" class="checkbox" value="1" <?php if(!empty($user['roles']['/typedata/dataadd'])) echo "checked";?>>是否能上传数据
            </label>
        </div>
    </div>

    <div class="form-group">
        <label class="col-xs-1"></label>
        <div class="col-xs-10">
            <label class="checkbox">
                <input type="checkbox" name="roles[/typedata/api]" class="checkbox" value="1" <?php if(!empty($user['roles']['/typedata/api'])) echo "checked";?> <?php if(!empty($user['roles']['/typedata/api'])) echo "checked";?>>是否能查看接口文档
            </label>
        </div>
    </div>
    <div class="form-group">
        <label class="col-xs-1"></label>
        <div class="col-xs-4">
            <label class="checkbox">
                给与查看的项目id(用|分割)
                <textarea name="roles[allow_type]" rows="2" cols="1" class="form-control"><?=@$user['roles']['allow_type']?></textarea>
            </label>
        </div>
    </div>

    <?php endif;?>
    <div class="form-group">
        <label class="col-xs-1"></label>
        <button type="submit" class="btn btn-flat btn-info btn-lg col-xs-2" style="margin-left: 15px;">提交</button>
    </div>
</form>