<form class="form-horizontal gameadd-form" role="form" action="<?= $this->url->get('admin/addadmin') ?>" method="post">
    <input type="hidden" name="<?= $this->security->getTokenKey() ?>" value="<?= $this->security->getToken() ?>"/>


    <div class="form-group">
        <label class="col-xs-2 control-label">用户名：</label>
        <div class="col-xs-10">
            <input type="text" name="name" placeholder="请输入游戏名称" class="form-control"   value="">
        </div>
    </div>
    <div class="form-group">
        <label class="col-xs-2 control-label">密码：</label>
        <div class="col-xs-10">
            <input type="text" name="passwd" placeholder="输入密码" class="form-control"   value="">
        </div>
    </div>

    <div class="form-group">
        <label class="col-xs-2 control-label"></label>
        <button type="submit" class="btn btn-flat btn-info btn-lg col-xs-10">提交</button>
    </div>
</form>